### ISSUE TITLE
Error occurred when executing KSampler:  Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 96, 64] to have 4 channels, but got 8 channels instead

### ISSUE THREAD

**Issue by azhaozz** [huchenlei/ComfyUI-IC-Light#1]
Hello, there is this problem to the k sampler, is there an error?

**Comment by huchenlei** [comment]
See https://github.com/huchenlei/ComfyUI-IC-Light#required-nodes.

You need to install https://github.com/huchenlei/ComfyUI-layerdiffuse first.
