### ISSUE TITLE
输入512，4通道，采样器报错

### ISSUE THREAD

**Issue by 807502278** [huchenlei/ComfyUI-IC-Light#2]
fg_bg_combine.json
!!! Exception during processing!!! Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 12, 64, 64] to have 4 channels, but got 12 channels instead
![image](https://github.com/huchenlei/ComfyUI-IC-Light/assets/46019416/05a69903-38be-4353-9ae6-f88e05f134bc)

fg_lightmap.json
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 8, 64, 64] to have 4 channels, but got 8 channels instead

fg.json
WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3])

**Comment by chaojie** [comment]
![image](https://github.com/huchenlei/ComfyUI-IC-Light/assets/701810/a98f9be5-5c4e-4d61-ac23-8e610f34d241)

**Comment by 807502278** [comment]
噢噢，我再试试

**Comment by huchenlei** [comment]
I added a common issues section in README here: https://github.com/huchenlei/ComfyUI-IC-Light#common-issues

**Comment by 807502278** [comment]
可以用了，就是物体会变色
