### ISSUE TITLE
help，Error occurred when executing KSampler:  Sizes of tensors must match except in dimension 1. Expected size 57 but got size 102 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by jokero3answer** [huchenlei/ComfyUI-IC-Light#5]
![image](https://github.com/huchenlei/ComfyUI-IC-Light/assets/130854108/9805722d-747e-4758-aee7-78b4c838a575)

[Diagnostics-1715394355.log](https://github.com/huchenlei/ComfyUI-IC-Light/files/15281374/Diagnostics-1715394355.log)

**Comment by huchenlei** [comment]
Based on following warning, you did not have layerdiffuse patching calc_weight.
```
WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3])
------------------------
```

Please see https://github.com/huchenlei/ComfyUI-IC-Light#important-required-nodes.
